/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "JS": {
      "key": "JS",
      "scope": "tags",
      "path": "/tag/JS/",
      "pageKeys": [
        "v-195f8ee4",
        "v-0e79b76e",
        "v-7fc58624",
        "v-0ac06fa4",
        "v-24657c6e",
        "v-c6e08d64",
        "v-0ce9650e",
        "v-0ad2308e",
        "v-18563f64",
        "v-dcc787a4",
        "v-7ebad7a4",
        "v-06a3180e",
        "v-777a18ae",
        "v-1000c6a4",
        "v-69de98a4",
        "v-e9594f24",
        "v-1758340e",
        "v-6d06788e",
        "v-1c0bf44e",
        "v-6bed4f64"
      ]
    },
    "Nginx": {
      "key": "Nginx",
      "scope": "tags",
      "path": "/tag/Nginx/",
      "pageKeys": [
        "v-c4bc17e4"
      ]
    },
    "CSS": {
      "key": "CSS",
      "scope": "tags",
      "path": "/tag/CSS/",
      "pageKeys": [
        "v-607a9624",
        "v-8a46cda4",
        "v-82f357e4"
      ]
    },
    "HTML": {
      "key": "HTML",
      "scope": "tags",
      "path": "/tag/HTML/",
      "pageKeys": [
        "v-cd1ba7e4",
        "v-2895106e",
        "v-19b73fe4"
      ]
    },
    "Cookie": {
      "key": "Cookie",
      "scope": "tags",
      "path": "/tag/Cookie/",
      "pageKeys": [
        "v-7a8c6ea4"
      ]
    },
    "VUE": {
      "key": "VUE",
      "scope": "tags",
      "path": "/tag/VUE/",
      "pageKeys": [
        "v-338c2d4e",
        "v-b51e66a4",
        "v-99f39764",
        "v-7dbc042e",
        "v-c5d3d9a4",
        "v-21c4a16e",
        "v-327c542e",
        "v-70af30ce",
        "v-c1a775e4"
      ]
    },
    "运算符": {
      "key": "运算符",
      "scope": "tags",
      "path": "/tag/运算符/",
      "pageKeys": [
        "v-1540500e"
      ]
    },
    "npm": {
      "key": "npm",
      "scope": "tags",
      "path": "/tag/npm/",
      "pageKeys": [
        "v-3f0bd80e",
        "v-1fad6cee"
      ]
    },
    "组件": {
      "key": "组件",
      "scope": "tags",
      "path": "/tag/组件/",
      "pageKeys": [
        "v-01608d0e"
      ]
    },
    "正则": {
      "key": "正则",
      "scope": "tags",
      "path": "/tag/正则/",
      "pageKeys": [
        "v-06994624"
      ]
    }
  },
  "categories": {
    "前端小笔记": {
      "key": "前端小笔记",
      "scope": "categories",
      "path": "/categories/前端小笔记/",
      "pageKeys": [
        "v-195f8ee4",
        "v-0e79b76e",
        "v-7fc58624",
        "v-0ac06fa4",
        "v-24657c6e",
        "v-607a9624",
        "v-8a46cda4",
        "v-c6e08d64",
        "v-0ce9650e",
        "v-cd1ba7e4",
        "v-0ad2308e",
        "v-18563f64",
        "v-7ebad7a4",
        "v-06a3180e",
        "v-777a18ae",
        "v-1000c6a4",
        "v-69de98a4",
        "v-e9594f24",
        "v-1758340e",
        "v-1540500e",
        "v-1c0bf44e",
        "v-6bed4f64"
      ]
    },
    "问题集中营": {
      "key": "问题集中营",
      "scope": "categories",
      "path": "/categories/问题集中营/",
      "pageKeys": [
        "v-c4bc17e4"
      ]
    },
    "Cookie": {
      "key": "Cookie",
      "scope": "categories",
      "path": "/categories/Cookie/",
      "pageKeys": [
        "v-7a8c6ea4"
      ]
    },
    "排序": {
      "key": "排序",
      "scope": "categories",
      "path": "/categories/排序/",
      "pageKeys": [
        "v-dcc787a4"
      ]
    },
    "VUE": {
      "key": "VUE",
      "scope": "categories",
      "path": "/categories/VUE/",
      "pageKeys": [
        "v-338c2d4e",
        "v-b51e66a4",
        "v-99f39764",
        "v-7dbc042e",
        "v-c5d3d9a4",
        "v-21c4a16e",
        "v-327c542e",
        "v-70af30ce",
        "v-c1a775e4"
      ]
    },
    "CSS": {
      "key": "CSS",
      "scope": "categories",
      "path": "/categories/CSS/",
      "pageKeys": [
        "v-82f357e4"
      ]
    },
    "Promise": {
      "key": "Promise",
      "scope": "categories",
      "path": "/categories/Promise/",
      "pageKeys": [
        "v-6d06788e"
      ]
    },
    "npm": {
      "key": "npm",
      "scope": "categories",
      "path": "/categories/npm/",
      "pageKeys": [
        "v-3f0bd80e",
        "v-1fad6cee"
      ]
    },
    "组件": {
      "key": "组件",
      "scope": "categories",
      "path": "/categories/组件/",
      "pageKeys": [
        "v-01608d0e"
      ]
    },
    "正则": {
      "key": "正则",
      "scope": "categories",
      "path": "/categories/正则/",
      "pageKeys": [
        "v-06994624"
      ]
    },
    "HTML": {
      "key": "HTML",
      "scope": "categories",
      "path": "/categories/HTML/",
      "pageKeys": [
        "v-2895106e",
        "v-19b73fe4"
      ]
    }
  },
  "timeline": {}
}